#!/bin/sh 

#cd /home/bsh/Apps/Ulanmedia2/

#pipenv run gunicorn --chdir dashboard/server/json_server/ -t 300 -w 5 -b 127.0.0.1:5001 server:app

pipenv run python /home/bsh/Apps/Ulanmedia2/dashboard/server/json_server/server.py

