from update_traffic_click_id_in_conversions_table import update_traffic_click_id_in_conversions_table

update_traffic_click_id_in_conversions_table(0)
print("conversions table updated with mgid click ids")
